apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policy-generator-blog
  namespace: policies-appset
spec:
  destination:
    namespace: policy-generator-blog
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kustomize
    repoURL: https://github.com/ch-stark/grc-policy-generator-blog.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
